baseURL = 'https://phanhung.blog/'
languageCode = 'vi-vn'
title = '#phanhungblog'
theme = 'PaperMod'

[params.homeInfoParams]
    Title = "Hi there üëã"
    Content = "Welcome to my blog."

[[params.socialIcons]]
    name = "discord"
    url = "https://discord.gg/phanhungblog"

[[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/phanhungblog"

[[params.socialIcons]]
    name = "email"
    url = "mailto:phanhungdev@gmail.com"

[params]
    showCodeCopyButtons = true # Hi·ªán n√∫t copy khi b·∫°n vi·∫øt code trong b√†i
    ShowToc = true # Hi·ªán m·ª•c l·ª•c t·ª± ƒë·ªông cho b√†i vi·∫øt d√†i
    TocOpen = false # M·∫∑c ƒë·ªãnh ƒë√≥ng m·ª•c l·ª•c cho g·ªçn