baseURL = 'https://phanhung.blog/'
languageCode = 'vi-vn'
title = 'H√πng Dev Blog'
theme = 'PaperMod'

[params.homeInfoParams]
    Title = "Ch√†o b·∫°n, m√¨nh l√† H√πng üëã"
    Content = "Blog chia s·∫ª v·ªÅ c√¥ng ngh·ªá, l·∫≠p tr√¨nh v√† nh·ªØng th·ª© hay ho m√¨nh h·ªçc ƒë∆∞·ª£c m·ªói ng√†y."

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/phan-hung-cua-ban" # Thay b·∫±ng link Github c·ªßa b·∫°n
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/ten-cua-ban"
[params]
    showCodeCopyButtons = true # Hi·ªán n√∫t copy khi b·∫°n vi·∫øt code trong b√†i
    ShowToc = true # Hi·ªán m·ª•c l·ª•c t·ª± ƒë·ªông cho b√†i vi·∫øt d√†i
    TocOpen = false # M·∫∑c ƒë·ªãnh ƒë√≥ng m·ª•c l·ª•c cho g·ªçn